# Generated by Django 4.2.15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1067_add_dashboardtemplate_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="cookieless_server_hash_mode",
            field=models.SmallIntegerField(choices=[(2, "Stateful")], default=2, null=True),
        ),
    ]
